/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceGui;

import a3.GerenciadorFunc;
import entidades.Funcionarios;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class CadastrarFuncionario extends javax.swing.JFrame {
    private GerenciadorFunc gerenciadorFunc;
    private int idFunc;
    /**
     * Creates new form CadastrarFuncionario
     */
    public CadastrarFuncionario() {
         this.gerenciadorFunc = gerenciadorFunc;
        initComponents();
    }

    
    
      private void preencherCampos(Funcionarios funcionarios) {
        nomeFuncField.setText(funcionarios.getNome());
        cpfFuncField.setText(funcionarios.getCpf());
        enderecoFuncField.setText(funcionarios.getEndereco());
        telefoneFuncField.setText(funcionarios.getTelefone());
        cargoField.setText(funcionarios.getCargo());
}
    
    
     private void limparCampos() {
        nomeFuncField.setText("");
        telefoneFuncField.setText("");
        cpfFuncField.setText("");
        cargoField.setText("");
        enderecoFuncField.setText("");
         
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        nomeFuncLb = new javax.swing.JLabel();
        cpfFuncLb = new javax.swing.JLabel();
        enderecoFuncLb = new javax.swing.JLabel();
        telFuncLb = new javax.swing.JLabel();
        cargoLb = new javax.swing.JLabel();
        nomeFuncField = new javax.swing.JTextField();
        cpfFuncField = new javax.swing.JTextField();
        enderecoFuncField = new javax.swing.JTextField();
        telefoneFuncField = new javax.swing.JTextField();
        cargoField = new javax.swing.JTextField();
        btnCadastrarFunc = new javax.swing.JButton();
        voltarCadCliente = new javax.swing.JButton();
        btnAtualizarFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(tbClientes);

        nomeFuncLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeFuncLb.setText("Insira o nome:");

        cpfFuncLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cpfFuncLb.setText("Insira o CPF: ");

        enderecoFuncLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enderecoFuncLb.setText("Insira o endereço:");

        telFuncLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telFuncLb.setText("Insira o Telefone: ");

        cargoLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargoLb.setText("Insira o Cargo: ");

        nomeFuncField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cpfFuncField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        enderecoFuncField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        telefoneFuncField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cargoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCadastrarFunc.setText("CADASTRAR");
        btnCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncActionPerformed(evt);
            }
        });

        voltarCadCliente.setBackground(new java.awt.Color(204, 0, 0));
        voltarCadCliente.setForeground(new java.awt.Color(255, 255, 255));
        voltarCadCliente.setText("VOLTAR");
        voltarCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadClienteActionPerformed(evt);
            }
        });

        btnAtualizarFunc.setText("ATUALIZAR");
        btnAtualizarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarCadCliente)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeFuncLb)
                            .addComponent(cpfFuncLb)
                            .addComponent(enderecoFuncLb)
                            .addComponent(telFuncLb)
                            .addComponent(cargoLb))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefoneFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nomeFuncField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(cpfFuncField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enderecoFuncField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cargoField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnCadastrarFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(btnAtualizarFunc)))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFuncLb)
                    .addComponent(nomeFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfFuncLb)
                    .addComponent(cpfFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoFuncLb)
                    .addComponent(enderecoFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFuncLb)
                    .addComponent(telefoneFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargoLb)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cargoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastrarFunc)
                        .addComponent(btnAtualizarFunc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(voltarCadCliente)
                .addGap(32, 32, 32)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncActionPerformed
        String nome = nomeFuncField.getText().trim();
        String cpf = cpfFuncField.getText().trim();
        String endereco = enderecoFuncField.getText().trim();
        String telefone = telefoneFuncField.getText().trim();
        String nivel = cargoField.getText().trim();

        if (validaCampos(nome, cpf, telefone, endereco, nivel)) {
            Funcionarios novoFuncionario = new Funcionarios();
            novoFuncionario.setNome(nome);
            novoFuncionario.setCpf(cpf);
            novoFuncionario.setEndereco(endereco);
            novoFuncionario.setTelefone(telefone);
            novoFuncionario.setCargo(nivel);

            gerenciadorFunc.inserirCliente(novoFuncionario);
           
            limparCampos();
        }
    }//GEN-LAST:event_btnCadastrarFuncActionPerformed

      public boolean validaCampos(String nome, String cpf, String telefone, String endereco, String nivel){
     if(nome.trim().isEmpty() || cpf.trim().isEmpty() || telefone.trim().isEmpty() || endereco.trim().isEmpty() || nivel.trim().isEmpty()){
         JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos para o cadastro", "ERRO", HEIGHT);
         return false;
     }
     return true;
     }
    
    
    private void voltarCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadClienteActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        this.dispose();
        tp.setVisible(true);
    }//GEN-LAST:event_voltarCadClienteActionPerformed

    private void btnAtualizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarFuncActionPerformed
        String nome = nomeFuncField.getText().trim();
        String cpf = cpfFuncField.getText().trim();
        String endereco = enderecoFuncField.getText().trim();
        String telefone = telefoneFuncField.getText().trim();
        String nivel = cargoField.getText().trim();

        if (validaCampos(nome, cpf, telefone, endereco, nivel)) {
            gerenciadorFunc.atualizarFunc(idFunc, nome, cpf, telefone, endereco, nivel);
            
            limparCampos();
        }
    }//GEN-LAST:event_btnAtualizarFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarFunc;
    private javax.swing.JButton btnCadastrarFunc;
    private javax.swing.JTextField cargoField;
    private javax.swing.JLabel cargoLb;
    private javax.swing.JTextField cpfFuncField;
    private javax.swing.JLabel cpfFuncLb;
    private javax.swing.JTextField enderecoFuncField;
    private javax.swing.JLabel enderecoFuncLb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeFuncField;
    private javax.swing.JLabel nomeFuncLb;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tbClientes;
    private javax.swing.JLabel telFuncLb;
    private javax.swing.JTextField telefoneFuncField;
    private javax.swing.JButton voltarCadCliente;
    // End of variables declaration//GEN-END:variables
}
